if [ -f ~/.bashrc ]
then
  source ~/.bashrc
fi

export GOPATH="$HOME/Code/go"
export PATH="$HOME/Code/go/bin:$HOME/Library/Haskell/bin:$HOME/.cargo/bin:$PATH"

# added by Anaconda3 5.2.0 installer
export PATH="/anaconda3/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kloisel/Documents/google-cloud-sdk/path.bash.inc' ]; then source '/Users/kloisel/Documents/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kloisel/Documents/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/kloisel/Documents/google-cloud-sdk/completion.bash.inc'; fi
export CXX=/usr/local/Cellar/gcc/8.2.0/bin/g++-8

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
