if [ -f ~/.bashrc ]
then
  source ~/.bashrc
fi

export GOPATH="$HOME/Code/go"
export PATH="$HOME/Code/go/bin:$HOME/Library/Haskell/bin:$HOME/.cargo/bin:$PATH"

# added by Anaconda3 5.2.0 installer
export PATH="/anaconda3/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kloisel/Documents/google-cloud-sdk/path.bash.inc' ]; then source '/Users/kloisel/Documents/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kloisel/Documents/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/kloisel/Documents/google-cloud-sdk/completion.bash.inc'; fi
export CXX=/usr/local/Cellar/gcc/8.2.0/bin/g++-8

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
export PATH="/usr/local/opt/openssl/bin:$PATH"

# Git autocomplete
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# Aliases
alias pip="python3 -m pip"
alias pip3="python3 -m pip"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
